### ISSUE TITLE
platform-roadmap question

### ISSUE THREAD

**Issue by amoskane** [tidepool-org/tidepool-org.github.io#67]
In " tidepool-org.github.io/_docs/platform-roadmap.md", line 32:
Items marked with _@@_ are lower priority given our current company priorities. Some of these (at least the ones not tied to Tidepool's deployment) might be good candidates for third party contributors to consider working on, as it's less likely that Tidepool's developers will be working on them soon. **These** items are marked with _@@3_.

What does 'These' refer to? Are items marked with _@@3_ ones that Tidepool devs are likely already doing?

**Comment by jebeck** [comment]
'These' refers to "good candidates for third party contributors" that are also "*less* likely that Tidepool’s developers will be working on soon." We'll try to clarify that in the doc soon.

If you're interested in contributing as a third-party developer @amoskane, I suggest you get in touch on our IRC channel - #tidepool on the Freenode server (chat.freenode.net). We're also trying out [a channel on Gitter](https://gitter.im/tidepool-org/chat) and may be using that exclusively instead of IRC soon.
